version: '3'
services:
  builder:
    build: .
    image: make-latex-ja
    container_name: make-latex-ja
    user: "${UID}:${GID}"
    tty: true
    working_dir: /workdir
    volumes:
      - ./:/workdir
